[project]
name = "idjl-gedi"
dynamic = ["version"]
description = "GEDI point cloud registration"
authors = [{ name = "IIT-Danieli Joint Lab" }]
requires-python = ">=3.9.0"
dependencies = [
    "pip",
    "gdown",
    "tensorboard",
    "protobuf",
    "numpy",
    "torchgeometry",
    "open3d",
]

[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = { attr = "gedi._version.__version__" }

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tool.pixi.dependencies]
tbb-devel = "*"
eigen = "*"
nanoflann = "*"
fmt = "*"

[tool.pixi.system-requirements]
libc   = { family = "glibc", version = "2.31" }

# Python versions distribution
[tool.pixi.feature.py39.dependencies]
python = "3.9.*"
[tool.pixi.feature.py310.dependencies]
python = "3.10.*"
[tool.pixi.feature.py311.dependencies]
python = "3.11.*"
[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

# Torch versions distribution
[tool.pixi.feature.torch-cpu.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]
[tool.pixi.feature.torch-cu118.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu118"]
[tool.pixi.feature.torch-cu121.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu121"]
[tool.pixi.feature.torch-cu124.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu124"]
[tool.pixi.feature.torch-cu126.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu126"]
[tool.pixi.feature.torch-cu128.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu128"]
[tool.pixi.feature.torch-cu129.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu129"]

[tool.pixi.environments]
py39-cpu = ["py39", "torch-cpu"]
py39-cu118 = ["py39", "torch-cu118"]
py39-cu121 = ["py39", "torch-cu121"]
py39-cu124 = ["py39", "torch-cu124"]
py39-cu126 = ["py39", "torch-cu126"]
py39-cu128 = ["py39", "torch-cu128"]
py39-cu129 = ["py39", "torch-cu129"]
py310-cpu = ["py310", "torch-cpu"]
py310-cu118 = ["py310", "torch-cu118"]
py310-cu121 = ["py310", "torch-cu121"]
py310-cu124 = ["py310", "torch-cu124"]
py310-cu126 = ["py310", "torch-cu126"]
py310-cu128 = ["py310", "torch-cu128"]
py310-cu129 = ["py310", "torch-cu129"]
py311-cpu = ["py311", "torch-cpu"]
py311-cu118 = ["py311", "torch-cu118"]
py311-cu121 = ["py311", "torch-cu121"]
py311-cu124 = ["py311", "torch-cu124"]
py311-cu126 = ["py311", "torch-cu126"]
py311-cu128 = ["py311", "torch-cu128"]
py311-cu129 = ["py311", "torch-cu129"]
py312-cpu = ["py312", "torch-cpu"]
py312-cu118 = ["py312", "torch-cu118"]
py312-cu121 = ["py312", "torch-cu121"]
py312-cu124 = ["py312", "torch-cu124"]
py312-cu126 = ["py312", "torch-cu126"]
py312-cu128 = ["py312", "torch-cu128"]
py312-cu129 = ["py312", "torch-cu129"]

[tool.pixi.target.linux.dependencies]
libgcc = "<=11.3.0"  # To support building wheels compatible with glibc >= 2.35 (default conda-forge build targets >= 2.39, while e.g. Ubuntu 22.04 comes with glibc 2.35).
gcc = "<=11.3.0"

[tool.pixi.pypi-dependencies]
build = "*"
wheel = "*"
ninja = "*"
torch = "*"

[tool.pixi.target.win.pypi-dependencies]
delvewheel = "*"

[tool.pixi.target.linux.pypi-dependencies]
patchelf = "*"
auditwheel = "*"

[tool.pixi.tasks]
wheel-build-gedi = { cmd = "python -m build --wheel --outdir dist --no-isolation && python wheel-repair.py" }
wheel-build-windows = { depends-on = ["wheel-build-gedi"], cmd = "delvewheel repair dist\\*.whl -w Release --exclude c10.dll --exclude c10_cuda.dll --exclude torch_cpu.dll --exclude torch_cuda.dll  --exclude torch_python.dll --exclude cudart64_12.dll --exclude cudnn64_9.dll && rm -rf dist" }
wheel-build-linux = { depends-on = ["wheel-build-gedi"], cmd = "auditwheel repair dist/*.whl -w Release --exclude libc10.so --exclude libc10_cuda.so --exclude libtorch.so --exclude libtorch_cpu.so --exclude libtorch_cuda.so --exclude libtorch_python.so --exclude libcudart.so.12 --exclude libcudnn.so.9 && rm -rf dist" }